// scripts/import-aer.ts
// Докопировывает наши файлы поверх engine/ после `surfer import`.
// Запуск: bun scripts/import-aer.ts
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const engine = join(root, "engine");

async function copyIfExists(srcRel: string, destRel: string): Promise<void> {
  const src = join(root, srcRel);
  const dest = join(engine, destRel);
  const srcFile = Bun.file(src);
  // cp -r через Bun.$ для директорий; проверяем существование
  const exists = await srcFile.exists().catch(() => false);
  // Для директорий exists() может врать — пробуем ls через Glob
  const glob = new Bun.Glob("**/*");
  let hasAny = exists;
  if (!hasAny) {
    try {
      for await (const _ of glob.scan({ cwd: src, onlyFiles: false })) {
        hasAny = true;
        break;
      }
    } catch {
      hasAny = false;
    }
  }
  if (!hasAny) {
    console.log(`[aer/import] skip (no src): ${srcRel}`);
    return;
  }
  await Bun.$`mkdir -p ${dirname(dest)} && cp -r ${src} ${dest}`.quiet();
  console.log(`[aer/import] ${srcRel} -> engine/${destRel}`);
}

const engineMarker = Bun.file(join(engine, "moz.build"));
const engineDirExists = await Bun.$`test -d ${engine} && echo yes || echo no`.text();
if (!engineDirExists.includes("yes")) {
  console.error("[aer/import] engine/ not found. Сначала `bun run download`.");
  process.exit(1);
}
void engineMarker;

await copyIfExists("src/zen", "browser/components/aer");
// НЕ копируем branding/aer: заглушка без иконок, а surfer build при виде
// engine/browser/branding/aer перестал бы использовать unofficial и упал бы
// на configure. Настоящий брендинг ляжет в configs/branding/aer/ позже.
await copyIfExists("configs/common/mozconfig", "mozconfig-aer-common");
await copyIfExists("configs/windows/mozconfig", ".mozconfig");

// Prefs: YAML -> firefox.js snippet (примитивно, без зависимостей)
const yamlPath = join(root, "prefs/aer/browser.yaml");
const yamlFile = Bun.file(yamlPath);
if (await yamlFile.exists()) {
  const text = await yamlFile.text();
  const prefs: string[] = [];
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const m = t.match(/^([\w.\-]+):\s*(.+)$/);
    if (!m) continue;
    const [, key, raw] = m as unknown as [string, string, string];
    let val: string;
    if (raw === "true" || raw === "false") val = raw;
    else if (raw !== "" && !isNaN(Number(raw))) val = raw;
    else val = `"${raw.replace(/"/g, '\\"')}"`;
    prefs.push(`pref("${key}", ${val});`);
  }
  const out = join(engine, "browser/components/aer/aer-prefs.js");
  await Bun.$`mkdir -p ${dirname(out)}`.quiet();
  await Bun.write(out, "// auto-generated by scripts/import-aer.ts\n" + prefs.join("\n") + "\n");
  console.log(`[aer/import] prefs: ${prefs.length} -> browser/components/aer/aer-prefs.js`);
}

console.log("[aer/import] done");
